{
 "title": "4 - ML Performance",
 "tags": [
  "machine learning",
  "model",
  "airlines"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Model comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "R2 Score",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_model_r2_score{status=\"production\"}",
     "legendFormat": "Production"
    },
    {
     "expr": "ml_model_r2_score{status=\"challenger\"}",
     "legendFormat": "Challenger"
    }
   ]
  },
  {
   "title": "MAE (min)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_model_mae{status=\"production\"}",
     "legendFormat": "Production"
    },
    {
     "expr": "ml_model_mae{status=\"challenger\"}",
     "legendFormat": "Challenger"
    }
   ]
  },
  {
   "title": "RMSE (min)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqrt(ml_model_mse{status=\"production\"})",
     "legendFormat": "Production"
    },
    {
     "expr": "sqrt(ml_model_mse{status=\"challenger\"})",
     "legendFormat": "Challenger"
    }
   ]
  },
  {
   "title": "Max Error (min)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_model_max_error{status=\"production\"}",
     "legendFormat": "Production"
    },
    {
     "expr": "ml_model_max_error{status=\"challenger\"}",
     "legendFormat": "Challenger"
    }
   ]
  },
  { "title": "Evolution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Model Metrics Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ml_model_r2_score{status=\"production\"}",
     "legendFormat": "R2"
    },
    {
     "expr": "ml_model_mae{status=\"production\"}",
     "legendFormat": "MAE"
    },
    {
     "expr": "sqrt(ml_model_mse{status=\"production\"})",
     "legendFormat": "RMSE"
    },
    {
     "expr": "ml_model_max_error{status=\"production\"}",
     "legendFormat": "Max Error"
    }
   ]
  }
 ]
}